FROM ruby:3.1.0-alpine3.15

WORKDIR /app
ENV RAILS_ENV development

RUN apk add --no-cache --update \
        bash build-base libcurl nodejs yarn postgresql14-client libpq-dev \
        libstdc++ libx11 libxrender libxext fontconfig freetype

COPY Gemfile Gemfile.lock /app/
RUN gem install bundler && \
    bundle install --jobs `grep -c processor /proc/cpuinfo` --retry 5

RUN apk del build-base

CMD ["puma", "-C", "config/puma.rb"]
