development:
  adapter: postgresql
  host: database
  database: meuhorario
  pool: 10
  username: meuhorario
  password: password

test:
  adapter: postgresql
  host: database
  database: meuhorario_test
  pool: 10
  username: meuhorario
  password: password

production:
  adapter: postgresql
  host: database
  database: meuhorario
  pool: 10
  username: "<%= ENV["DB_USER"] %>"
  password: "<%= ENV["DB_PASSWORD"] %>"
