development:
  adapter: postgresql
  database: meuhorario_dev
  pool: 5
  username: meuhorario
  password: UbdTL3XB

test:
  adapter: postgresql
  database: meuhorario_test
  pool: 5
  username: meuhorario
  password: UbdTL3XB